package com.spring.jdbc.app.common;

public interface DBQueries {

	String SELECT_USER_BY_ID = "SELECT ID, NAME, LOCATION FROM USERS WHERE ID=? ";
	String SELECT_ALL_USERS = "SELECT ID, NAME, LOCATION FROM USERS";
	String INSERT_INTO_USERS = "INSERT INTO USERS (NAME, LOCATION ) VALUES(?,?)";
	String DELETE_USER_BY_ID = "DELETE FROM USERS WHERE ID=? ";
	String UPDATE_USER_BY_ID = "UPDATE USERS SET  NAME=?, LOCATION=? WHERE ID=? ";
	String LATEST_USER = "SELECT  ID ,NAME ,LOCATION  FROM USERS WHERE ID=(SELECT MAX(ID) FROM USERS)";

}

