INSERT INTO USERS(ID, NAME, LOCATION) VALUES (101, 'Anuradha','Hyderabad');
INSERT INTO USERS(ID, NAME, LOCATION) VALUES (105, 'Latha','Vijayawada');
INSERT INTO USERS(ID, NAME, LOCATION) VALUES (102, 'Praveen','Visakapatnam');
INSERT INTO USERS(ID, NAME, LOCATION) VALUES (103, 'Priyanka','Hyderabad');
INSERT INTO USERS(ID, NAME, LOCATION) VALUES (104, 'Siva','Vizag');
INSERT INTO USERS(ID, NAME, LOCATION) VALUES (106, 'Madhav','Hyderabad');



